In [2]:
import numpy as np

In [36]:
ls

ADE_val_00000001.npy                intersec3.npy        pred_img4.npy
ADE_val_00000001.png                intersec4.npy        pred_img5.npy
ADE_val_00000974_mitbs.npy          intersec5.npy        pred_img6.npy
ADE_val_00000974_psp.npy            intersec6.npy        pred_img7.npy
area_lab0.npy                       intersec7.npy        pred_img8.npy
area_lab1.npy                       intersec8.npy        pred_img9.npy
area_lab2.npy                       intersec9.npy        pytorch_log
area_lab3.npy                       iou_final.npy        pytorch_log_iou
area_lab4.npy                       local_intersec0.npy  segs_img0.npy
area_lab5.npy                       local_intersec1.npy  segs_img1.npy
area_lab6.npy                       local_intersec2.npy  segs_img2.npy
area_lab7.npy                       local_intersec3.npy  segs_img3.npy
area_lab8.npy                       local_intersec4.npy  segs_img4.npy
area_lab9.npy                       local_intersec5.npy  segs_img5.npy
area_p

In [46]:
int_p = np.load("intersec0.npy")
int_l = np.load("local_intersec0.npy").flatten()
uni_p = np.load("union0.npy")
uni_l = np.load("local_union0.npy").flatten()

In [47]:
np.sum(int_p - int_l)

0.0

In [48]:
np.sum(uni_p - uni_l)

113256.0

In [49]:
print(uni_p[uni_p > 0])
print(np.where(uni_p > 0))
print(uni_l[uni_l > 0])
print(np.where(uni_l > 0))
uni_l_p = uni_l[uni_l > 0][0:7]
uni_p_p = uni_p[uni_p > 0][0:7]

[  21597.  124220.  135240.   11820.    1755.   54722.   10713.  113256.]
(array([ 0,  1,  2,  4,  6,  9, 17, 25]),)
[  21597.  124220.  135240.   11820.    1755.   54722.   10713.]
(array([ 0,  1,  2,  4,  6,  9, 17]),)


In [45]:
np.sum(pred_img0 == 25)

113256

In [14]:
area_pred0 = np.load("area_pred0.npy")
area_lab0 = np.load("area_lab0.npy")
pred_img0 = np.load("pred_img0.npy")
segs_img0 = np.load("segs_img0.npy")

In [18]:
print(area_pred0[0])
print(area_lab0[0])

18737.0
14538.0


In [24]:
pred_img0_r = pred_img0.reshape((512,683))

In [31]:
pred_img_l = np.load("debug_pred_0.npy")
seg_img_l = np.load("debug_val_0.npy")
pred_img_l[seg_img_l < 0] = -1

In [33]:
np.sum(pred_img0_r - pred_img_l)

0.0

In [29]:
seg_img_l

array([[ 2.,  2.,  2., ..., -1., -1., -1.],
       [ 2.,  2.,  2., ..., -1., -1., -1.],
       [ 2.,  2.,  2., ...,  2.,  2., -1.],
       ..., 
       [ 9.,  9.,  9., ...,  6.,  6., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.]], dtype=float32)

In [34]:
iou = np.load("../iou_final.npy")

array([[ 0.72728607],
       [ 0.31334911],
       [ 0.98412769],
       [ 0.90805343],
       [ 0.71281422],
       [ 0.86674293],
       [ 0.53331446],
       [ 0.        ],
       [ 0.13341724],
       [ 0.95431907],
       [ 0.        ],
       [ 0.        ],
       [ 0.39602237],
       [ 0.        ],
       [ 0.26122284],
       [ 0.05364466],
       [ 0.38947901],
       [ 0.41738661],
       [ 0.        ],
       [ 0.46205487],
       [ 0.77428615],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.77498343],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.3240878 ],
       [ 0.        ],
       [ 0